teleport:
  world: "world"
  x: 100
  y: 65
  z: 100

tiers:
  common:
    stack: 16
    color: "§f"

  uncommon:
    stack: 12
    color: "§a"

  rare:
    stack: 8
    color: "§9"

  legendary:
    stack: 4
    color: "§6"

relics:

  diamond_relic:
    tier: rare
    name: "§9✦ Diamond Relic"
    lore:
      - "§7Right click a relic chest"
      - "§7to receive rewards"

    rewards:

      - command: "give {player} diamond 40"
        chance: 60
        message: "§aYou received 40 diamonds!"

      - command: "give {player} emerald 20"
        chance: 40
        message: "§aYou received 20 emeralds!"
